// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoyrqpohxyajusmgawfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpveXJxcG9oeHlhanVzbWdhd2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjU5NTUsImV4cCI6MjA3MzcwMTk1NX0.AlJKFzePM5P4yXHQ8_k5LbBgC4vAVH0IHBZbpQNrj-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});